services:
  postgres-blackjack:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: bd_battleship
    ports:
      - "2011:5432"
    volumes:
      - postgres_data_blackjack:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mongo-blackjack:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "2012:27017"
    volumes:
      - mongo_data_blackjack:/data/db

  backend-blackjack:
    build:
      context: ../back_end
      dockerfile: Dockerfile
    container_name: backend-blackjack
    restart: unless-stopped
    env_file:
      - ../back_end/.env.prod
    depends_on:
      - postgres-blackjack
      - mongo-blackjack
    ports:
      - "2013:3333"
      - "2014:3334"


  frontend-blackjack:
    build:
      context: ../front-end
      dockerfile: Dockerfile
    ports:
      - "2015:80"
    container_name: frontend-blackjack
    restart: unless-stopped
    depends_on:
      - backend-blackjack

volumes:
  postgres_data_blackjack:
  mongo_data_blackjack:
